name: "Get Description"

author: "ryohidaka"

description: "GitHub Actions to get repository description."

branding:
  color: green
  icon: send

inputs:

outputs:

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
