name: "Get Description"

author: "ryohidaka"

description: "GitHub Actions to get repository description."

branding:
  color: white
  icon: align-left

inputs:
  token:
    description: "GitHub Token for API access"
    required: true

  repository:
    description: "The repository in the format owner/repo (default: current repository)"
    required: false
    default: ${{ github.repository }}

outputs:
  description:
    description: "The description of the repository"
    value: ${{ steps.get_description.outputs.description }}

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get repository description
      id: get_description
      run: |
        ${{ github.action_path }}/scripts/get-description.sh \
          "${{ inputs.repository }}" \
          "$GITHUB_TOKEN"
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      shell: bash
